services:
  backend:
    image: rudnevo-backend
    build:
      context: ./backend
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
  frontend:
    image: rudnevo-frontend
    build:
      context: ./frontend
    ports:
      - "5000:5000"
    environment:
      BACKEND_HOST: backend
      BACKEND_PORT: 8000
    depends_on:
      - backend
  db:
    image: postgres:16.0
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
