version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: rudnevo_db
      POSTGRES_USER: rudnevo_user
      POSTGRES_PASSWORD: "N-5itQCThk7WFOVqdCwFhH9hnsAMOclw"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    depends_on:
      - db
    volumes:
      - ./backend/media:/app/media
    ports:
      - "8000:8000"
    restart: always

  admin-panel:
    build:
      context: ./admin-panel
    depends_on:
      - backend
    env_file:
      - ./admin-panel/.env
    ports:
      - "5000:5000"
    restart: always

volumes:
  postgres_data: